version: '3'
services:
  backend:
    build: backend/
    #image: ${repository_url}/backend:latest
    image: rsxo/backend:latest
    expose:
      - "80"
  react-bff:
    build: react-bff/
    #image: ${repository_url}/react-bff:v1.1
    image: rsxo/react-bff:v1.1
    ports:
      - "80"
    environment:
      BACKEND_ALB_URL: http://backend/greeting

