spring:
  application:
    name: react-bff

---
spring:
  profiles: default
backend:
  alb:
    url: http://localhost:8080/greeting

server:
  port: 8080

---
spring:
  profiles: docker

server:
  port: 80
backend:
  alb:
    url: ${BACKEND_ALB_URL}